ip: 127.0.0.1
port: 10800
serverPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5dJFHaPLpEO6ZmgHN2WEWDYL+6xltVoWNJ6vuqfSgtyN88VmfSdWQwf8OIX8cJIt1Js55FzLcTF5iZO4jCeTPDXAGFRewwaDomTkYBp/5JVzb4Np2SPkNz5PHx9dAIYcZi94WnuJ1qcYs8laILPxg1EGMDmksGzI2bWa/pf2fFvCiVnjlJ6kt8y2ha0Ukc6XZT1qKKt8MIc2bDkQCDFvmJqlYTbD2C7+ro6kpVPR/zJ4A6WF1xqOujFeswM7cLOP4uI6WLOH7YAkRn3EyCmSeXptMA5jH/VF3xKI0KeRE2HkyEnW/SU65Z/DBbCTZ1gynNTlQ9sDKJP/zR2tVddScQIDAQAB
